# Generated by Django 2.1.3 on 2018-11-20 16:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DateTimeField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.ProcessItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='polygon',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='point',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='note',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='name',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='endtime',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
    ]
