# Generated by Django 2.1.3 on 2018-11-23 11:20

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='ContactRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Exploiting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Exploiting')),
            ],
        ),
        migrations.CreateModel(
            name='HorizonBuild',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.HorizonBuild')),
            ],
        ),
        migrations.CreateModel(
            name='HorizonDesign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.HorizonDesign')),
            ],
        ),
        migrations.CreateModel(
            name='HorizonInstall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.DateTimeField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.HorizonInstall')),
            ],
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Intent')),
            ],
        ),
        migrations.CreateModel(
            name='KindRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Occupying',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Occupying')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Polygon')),
            ],
        ),
        migrations.CreateModel(
            name='PresentState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.PresentState')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectedState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.ProjectedState')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.ProjectName')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.SiteName')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.KindRef')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('index', models.IntegerField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Workflow')),
            ],
        ),
        migrations.AddField(
            model_name='presentstate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='presentstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polygon',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='point',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='point',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occupying',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='occupying',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occupying',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.ContactRef'),
        ),
        migrations.AddField(
            model_name='intent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='intent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horizoninstall',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='horizoninstall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horizondesign',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='horizondesign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horizonbuild',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='horizonbuild',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploiting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='exploiting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exploiting',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.ContactRef'),
        ),
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='developer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developer',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.ContactRef'),
        ),
        migrations.AddField(
            model_name='contact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
