# Generated by Django 2.1.3 on 2018-11-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perspective_pp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processitem',
            name='process',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Process'),
            preserve_default=False,
        ),
    ]
