# Generated by Django 2.1.3 on 2018-11-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perspective_pp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Contact'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Developer'),
        ),
        migrations.AlterField(
            model_name='exploiting',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Exploiting'),
        ),
        migrations.AlterField(
            model_name='horizonbuild',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.HorizonBuild'),
        ),
        migrations.AlterField(
            model_name='horizondesign',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.HorizonDesign'),
        ),
        migrations.AlterField(
            model_name='horizoninstall',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.HorizonInstall'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Intent'),
        ),
        migrations.AlterField(
            model_name='occupying',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Occupying'),
        ),
        migrations.AlterField(
            model_name='point',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Point'),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Polygon'),
        ),
        migrations.AlterField(
            model_name='presentstate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.PresentState'),
        ),
        migrations.AlterField(
            model_name='projectedstate',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.ProjectedState'),
        ),
        migrations.AlterField(
            model_name='projectname',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.ProjectName'),
        ),
        migrations.AlterField(
            model_name='sitename',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.SiteName'),
        ),
    ]
