# Generated by Django 2.1.3 on 2018-11-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perspective_pp', '0002_auto_20181123_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.ContactRef'),
        ),
    ]
