# Generated by Django 2.1.3 on 2018-11-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perspective_pp', '0003_auto_20181123_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horizonbuild',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='horizondesign',
            name='value',
            field=models.IntegerField(),
        ),
    ]
