# Generated by Django 2.1.3 on 2018-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perspective_pp', '0003_auto_20181121_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
            ],
        ),
    ]
