# Generated by Django 2.1.3 on 2018-11-26 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perspective_pp', '0004_auto_20181123_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='InOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(choices=[('i', 'In'), ('o', 'Out')], max_length=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.InOut')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='perspective_pp.Year')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perspective_pp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='exploiting',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='horizonbuild',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='horizondesign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='horizoninstall',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='intent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='occupying',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='point',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='polygon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='presentstate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectedstate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectname',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitename',
            options={'ordering': ['-created_at']},
        ),
    ]
